environment: production

image:
  repo: web3f/polkadot-watcher-auctions
  tag: v0.1.0

config:
  endpoint: "wss://cc3-3.kusama.network"
  port: 3000
  logLevel: info
  debug:
    enabled: false
    forceInitialWrite: false
  exportDir: "/app/data-csv"
  endSessionBlockDistance: 20
  bucketUpload:
    enabled: false
    gcpServiceAccount: '/app/service-account/credentials.json'
    gcpProject: ''
    gcpBucketName: '' 
  cronjob:
    enabled: true  

secret:
  gcpServiceAccountValue: |
    {"type":"service_account","project_id":"xxx","private_key_id":"xxx","private_key":"xxx"}
    
resources: 
  requests:
    cpu: "800m"
    memory: "1Gi"
  limits:
    cpu: "2200m"
    memory: "2Gi" 
