endpoint: "wss://rococo-rpc.polkadot.io/"
port: 3000
logLevel: info
debug:
  enabled: false
subscriber:
  modules:
    event:
      enabled: true
    block:
      enabled: false
persister:
  mongo:
    uri: 'mongodb://localhost:27017/auctions'